export default [
  {
    _id: "M101",
    name: "Introduction to Rocket Propulsion",
    description: "Comprehensive introduction to the fundamental physics and engineering principles governing rocket propulsion systems and various engine configurations.",
    course: "RS101",
    lessons: [
      {
        _id: "L101",
        name: "History of Rocketry",
        description: "Explore the evolution of rocket technology from ancient Chinese fireworks to modern space exploration milestones.",
        module: "M101",
      },
      {
        _id: "L102",
        name: "Rocket Propulsion Fundamentals",
        description: "Master Newton's laws, momentum conservation, and thrust equations essential for rocket propulsion analysis.",
        module: "M101",
      },
      {
        _id: "L103",
        name: "Rocket Engine Types",
        description: "Comparative analysis of solid, liquid, hybrid, and electric propulsion systems with their applications.",
        module: "M101",
      },
    ],
  },
  {
    _id: "M102",
    name: "Fuel and Combustion",
    description: "Advanced study of propellant chemistry, combustion dynamics, and thermochemical processes in rocket engines.",
    course: "RS101",
    lessons: [
      {
        _id: "L201",
        name: "Rocket Fuel",
        description: "Comprehensive examination of cryogenic, hypergolic, and solid propellants with performance characteristics.",
        module: "M102",
      },
      {
        _id: "L202",
        name: "Combustion Processes",
        description: "Detailed analysis of combustion chamber dynamics, flame stability, and thermodynamic efficiency optimization.",
        module: "M102",
      },
      {
        _id: "L203",
        name: "Combustion Instability",
        description: "Investigation of acoustic coupling, pressure oscillations, and advanced mitigation strategies for stable operation.",
        module: "M102",
      },
    ],
  },
  {
    _id: "M103",
    name: "Nozzle Design",
    description: "Advanced engineering of converging-diverging nozzles for optimal thrust generation and performance characteristics.",
    course: "RS101",
    lessons: [
      {
        _id: "L301",
        name: "Nozzle Design",
        description: "Comprehensive study of bell, aerospike, and expansion-deflection nozzle geometries and their applications.",
        module: "M103",
      },
      {
        _id: "L302",
        name: "Nozzle Performance",
        description: "Analysis of expansion ratios, thrust coefficients, and altitude compensation for maximum efficiency.",
        module: "M103",
      },
      {
        _id: "L303",
        name: "Nozzle Optimization",
        description: "Computational methods and design techniques for mission-specific nozzle configuration and performance.",
        module: "M103",
      },
    ],
  },
  {
    _id: "M201",
    name: "Fundamentals of Aerodynamics",
    description: "Essential fluid dynamics principles governing atmospheric flight and spacecraft atmospheric interactions.",
    course: "RS102",
    lessons: [
      {
        _id: "L401",
        name: "Introduction to Aerodynamics",
        description: "Foundation concepts including continuity, Bernoulli's equation, and viscous flow phenomena.",
        module: "M201",
      },
      {
        _id: "L402",
        name: "Airfoil Design",
        description: "Comprehensive study of NACA profiles, laminar flow airfoils, and computational design methods.",
        module: "M201",
      },
      {
        _id: "L403",
        name: "Lift and Drag",
        description: "Mathematical modeling of aerodynamic forces, induced drag, and performance optimization techniques.",
        module: "M201",
      },
    ],
  },
  {
    _id: "M202",
    name: "Subsonic and Supersonic Flow",
    description: "Comprehensive analysis of compressible flow regimes and their impact on aerospace vehicle design.",
    course: "RS102",
    lessons: [
      {
        _id: "L501",
        name: "Subsonic Flow",
        description: "Detailed study of incompressible and compressible subsonic flow patterns and design considerations.",
        module: "M202",
      },
      {
        _id: "L502",
        name: "Supersonic Flow",
        description: "Analysis of shock wave formation, Prandtl-Meyer expansion, and hypersonic flow phenomena.",
        module: "M202",
      },
      {
        _id: "L503",
        name: "Transonic Flow",
        description: "Critical examination of mixed flow regimes, shock-boundary layer interactions, and buffeting effects.",
        module: "M202",
      },
    ],
  },
  {
    _id: "M203",
    name: "Aerodynamic Heating",
    description: "Thermal management strategies for high-speed atmospheric flight and atmospheric entry vehicles.",
    course: "RS102",
    lessons: [
      {
        _id: "L601",
        name: "Aerodynamic Heating",
        description: "Physics of stagnation point heating, boundary layer heat transfer, and radiative heating mechanisms.",
        module: "M203",
      },
      {
        _id: "L602",
        name: "Thermal Protection Systems",
        description: "Design and analysis of ablative shields, ceramic tiles, and active cooling systems for spacecraft.",
        module: "M203",
      },
      {
        _id: "L603",
        name: "Heat Transfer Mechanisms",
        description: "Comprehensive study of conduction, convection, and radiation in extreme aerospace environments.",
        module: "M203",
      },
    ],
  },
  {
    _id: "M301",
    name: "Spacecraft Structural Design",
    description: "Advanced structural engineering principles for spacecraft subjected to launch and space environment loads.",
    course: "RS103",
    lessons: [
      {
        _id: "L701",
        name: "Introduction to Spacecraft Structures",
        description: "Fundamental concepts of primary and secondary structures, load paths, and mass optimization strategies.",
        module: "M301",
      },
      {
        _id: "L702",
        name: "Materials for Spacecraft",
        description: "Properties and applications of composites, aluminum alloys, titanium, and exotic materials in space.",
        module: "M301",
      },
      {
        _id: "L703",
        name: "Structural Analysis Techniques",
        description: "Finite element methods, modal analysis, and fatigue life prediction for spacecraft components.",
        module: "M301",
      },
    ],
  },
  {
    _id: "M302",
    name: "Orbital Mechanics",
    description: "Mathematical foundations of satellite orbits, trajectory design, and interplanetary mission planning.",
    course: "RS103",
    lessons: [
      {
        _id: "L801",
        name: "Basics of Orbital Mechanics",
        description: "Kepler's laws, orbital elements, and two-body problem solutions for space missions.",
        module: "M302",
      },
      {
        _id: "L802",
        name: "Orbit Determination",
        description: "Statistical estimation techniques, tracking systems, and precise orbit prediction algorithms.",
        module: "M302",
      },
      {
        _id: "L803",
        name: "Mission Planning",
        description: "Delta-V budgets, launch windows, gravity assists, and optimal trajectory design methodologies.",
        module: "M302",
      },
    ],
  },
  {
    _id: "M303",
    name: "Spacecraft Systems Engineering",
    description: "Integrated approach to spacecraft design incorporating all subsystems and mission requirements.",
    course: "RS103",
    lessons: [
      {
        _id: "L901",
        name: "Spacecraft Systems Overview",
        description: "Comprehensive examination of power, thermal, communication, and attitude control subsystems.",
        module: "M303",
      },
      {
        _id: "L902",
        name: "Subsystem Integration",
        description: "Interface management, system verification, and testing protocols for complex spacecraft.",
        module: "M303",
      },
      {
        _id: "L903",
        name: "Systems Engineering Process",
        description: "Requirements analysis, trade studies, and risk management throughout the spacecraft lifecycle.",
        module: "M303",
      },
    ],
  },
  {
    _id: "M401",
    name: "Organic Molecules and Reactions",
    description: "Systematic study of carbon-based compounds, their structural features, and chemical transformations.",
    course: "RS104",
    lessons: [
      {
        _id: "L1001",
        name: "Introduction to Organic Chemistry",
        description: "Bonding theories, hybridization, and molecular representation methods in organic chemistry.",
        module: "M401",
      },
      {
        _id: "L1002",
        name: "Functional Groups",
        description: "Properties and reactivity patterns of alcohols, carbonyls, amines, and other key functional groups.",
        module: "M401",
      },
      {
        _id: "L1003",
        name: "Reaction Mechanisms",
        description: "Detailed analysis of substitution, elimination, and addition reaction pathways with stereochemical outcomes.",
        module: "M401",
      },
    ],
  },
  {
    _id: "M402",
    name: "Stereochemistry and Isomerism",
    description: "Three-dimensional aspects of molecular structure and their impact on chemical and biological properties.",
    course: "RS104",
    lessons: [
      {
        _id: "L1101",
        name: "Stereochemistry Basics",
        description: "Chirality, optical activity, and configuration determination using R/S and E/Z nomenclature.",
        module: "M402",
      },
      {
        _id: "L1102",
        name: "Types of Isomerism",
        description: "Structural, geometric, and optical isomerism with implications for drug design and synthesis.",
        module: "M402",
      },
      {
        _id: "L1103",
        name: "Stereochemical Analysis",
        description: "Advanced methods including circular dichroism, X-ray crystallography, and computational modeling.",
        module: "M402",
      },
    ],
  },
  {
    _id: "M403",
    name: "Spectroscopy and Analytical Techniques",
    description: "Modern instrumental methods for structure elucidation and quantitative analysis of organic compounds.",
    course: "RS104",
    lessons: [
      {
        _id: "L1201",
        name: "Introduction to Spectroscopy",
        description: "Electromagnetic radiation interaction with matter and fundamental spectroscopic principles.",
        module: "M403",
      },
      {
        _id: "L1202",
        name: "NMR Spectroscopy",
        description: "1H and 13C NMR theory, 2D techniques, and structure determination strategies.",
        module: "M403",
      },
      {
        _id: "L1203",
        name: "Mass Spectrometry",
        description: "Ionization methods, fragmentation patterns, and high-resolution mass spectrometry applications.",
        module: "M403",
      },
    ],
  },
  {
    _id: "M501",
    name: "Inorganic Chemistry Principles",
    description: "Comprehensive study of non-organic compounds, their electronic structures, and chemical behavior.",
    course: "RS105",
    lessons: [
      {
        _id: "L1301",
        name: "Introduction to Inorganic Chemistry",
        description: "Overview of main group and transition metal chemistry with industrial applications.",
        module: "M501",
      },
      {
        _id: "L1302",
        name: "Bonding Theories",
        description: "Valence bond, molecular orbital, and ligand field theories for inorganic systems.",
        module: "M501",
      },
      {
        _id: "L1303",
        name: "Periodic Trends",
        description: "Systematic variations in atomic properties, oxidation states, and chemical reactivity across periods.",
        module: "M501",
      },
    ],
  },
  {
    _id: "M502",
    name: "Coordination Chemistry",
    description: "Metal-ligand interactions, electronic structures, and applications of coordination complexes.",
    course: "RS105",
    lessons: [
      {
        _id: "L1401",
        name: "Coordination Compounds",
        description: "Nomenclature, isomerism, and stability of transition metal complexes with various ligands.",
        module: "M502",
      },
      {
        _id: "L1402",
        name: "Ligands and Complexes",
        description: "Chelation, macrocyclic effects, and design of selective metal-binding agents.",
        module: "M502",
      },
      {
        _id: "L1403",
        name: "Crystal Field Theory",
        description: "Electronic transitions, magnetic properties, and color in transition metal complexes.",
        module: "M502",
      },
    ],
  },
  {
    _id: "M503",
    name: "Bioinorganic Chemistry",
    description: "Essential roles of metal ions in biological processes and biomimetic chemistry applications.",
    course: "RS105",
    lessons: [
      {
        _id: "L1501",
        name: "Introduction to Bioinorganic Chemistry",
        description: "Overview of metalloproteins, metal homeostasis, and biogeochemical cycles.",
        module: "M503",
      },
      {
        _id: "L1502",
        name: "Metals in Biology",
        description: "Iron in oxygen transport, zinc fingers, and copper in electron transfer systems.",
        module: "M503",
      },
      {
        _id: "L1503",
        name: "Inorganic Drugs and Medicine",
        description: "Platinum anticancer agents, MRI contrast agents, and therapeutic radioisotopes.",
        module: "M503",
      },
    ],
  },
  {
    _id: "M601",
    name: "Thermodynamics in Chemistry",
    description: "Energy transformations, equilibrium, and spontaneity in chemical and physical processes.",
    course: "RS106",
    lessons: [
      {
        _id: "L1601",
        name: "Basic Thermodynamics",
        description: "State functions, enthalpy, entropy, and Gibbs free energy in chemical systems.",
        module: "M601",
      },
      {
        _id: "L1602",
        name: "Laws of Thermodynamics",
        description: "Mathematical formulation and practical applications of all four thermodynamic laws.",
        module: "M601",
      },
      {
        _id: "L1603",
        name: "Thermodynamic Processes",
        description: "Reversible and irreversible processes, phase transitions, and chemical equilibrium calculations.",
        module: "M601",
      },
    ],
  },
  {
    _id: "M602",
    name: "Chemical Kinetics",
    description: "Quantitative analysis of reaction rates, mechanisms, and catalysis in chemical systems.",
    course: "RS106",
    lessons: [
      {
        _id: "L1701",
        name: "Introduction to Chemical Kinetics",
        description: "Rate laws, order of reactions, and integrated rate equations for complex systems.",
        module: "M602",
      },
      {
        _id: "L1702",
        name: "Reaction Mechanisms",
        description: "Elementary steps, rate-determining steps, and steady-state approximation methods.",
        module: "M602",
      },
      {
        _id: "L1703",
        name: "Factors Affecting Reaction Rates",
        description: "Temperature effects, catalysis, and solvent influences on reaction kinetics.",
        module: "M602",
      },
    ],
  },
  {
    _id: "M603",
    name: "Quantum Chemistry and Spectroscopy",
    description: "Application of quantum mechanics to molecular structure, bonding, and spectroscopic properties.",
    course: "RS106",
    lessons: [
      {
        _id: "L1801",
        name: "Basics of Quantum Chemistry",
        description: "Wave functions, Schrödinger equation, and quantum mechanical postulates for molecules.",
        module: "M603",
      },
      {
        _id: "L1802",
        name: "Molecular Orbitals",
        description: "LCAO method, Hückel theory, and computational approaches to electronic structure.",
        module: "M603",
      },
      {
        _id: "L1803",
        name: "Spectroscopic Techniques",
        description: "Rotational, vibrational, and electronic spectroscopy with selection rules and applications.",
        module: "M603",
      },
    ],
  },
  {
    _id: "M701",
    name: "Intro to Ancient Civilizations",
    description: "Comprehensive survey of ancient cultures and their linguistic heritage across Middle-earth.",
    course: "RS107",
    lessons: [
      {
        _id: "L1901",
        name: "Ancient Civilizations Overview",
        description: "Historical timeline and cultural achievements of Elvish, Dwarvish, and Mannish civilizations.",
        module: "M701",
      },
      {
        _id: "L1902",
        name: "Language Development",
        description: "Evolution of linguistic families from proto-languages to modern dialectical variations.",
        module: "M701",
      },
      {
        _id: "L1903",
        name: "Scripts and Inscriptions",
        description: "Decipherment techniques for Tengwar, Cirth, and other ancient writing systems.",
        module: "M701",
      },
    ],
  },
  {
    _id: "M702",
    name: "Linguistic Structures",
    description: "Detailed grammatical analysis and structural features of constructed Middle-earth languages.",
    course: "RS107",
    lessons: [
      {
        _id: "L2001",
        name: "Phonetics and Phonology",
        description: "Sound systems, phonological processes, and prosodic features of Elvish languages.",
        module: "M702",
      },
      {
        _id: "L2002",
        name: "Morphology and Syntax",
        description: "Word formation, inflectional systems, and syntactic structures in ancient tongues.",
        module: "M702",
      },
      {
        _id: "L2003",
        name: "Semantics and Pragmatics",
        description: "Meaning construction, metaphorical systems, and contextual language use in literature.",
        module: "M702",
      },
    ],
  },
  {
    _id: "M703",
    name: "Cultural Contexts",
    description: "Sociolinguistic analysis of language use, power dynamics, and cultural identity in Middle-earth.",
    course: "RS107",
    lessons: [
      {
        _id: "L2101",
        name: "Cultural Significance",
        description: "Language as cultural artifact, ritual speech, and linguistic taboos in different societies.",
        module: "M703",
      },
      {
        _id: "L2102",
        name: "Language and Identity",
        description: "Linguistic markers of ethnic identity, social status, and regional affiliation.",
        module: "M703",
      },
      {
        _id: "L2103",
        name: "Preservation of Ancient Languages",
        description: "Documentation methods, revitalization strategies, and digital preservation techniques.",
        module: "M703",
      },
    ],
  },
  {
    _id: "M801",
    name: "Diplomatic History of Middle-earth",
    description: "Comprehensive analysis of treaties, alliances, and diplomatic relations throughout the Ages.",
    course: "RS108",
    lessons: [
      {
        _id: "L2201",
        name: "Historical Alliances",
        description: "Formation and dissolution of major alliances from the First Age through the Fourth Age.",
        module: "M801",
      },
    ],
  },
  {
    _id: "M802",
    name: "Inter-species Communication",
    description: "Protocols, challenges, and successes in diplomatic exchanges between diverse Middle-earth peoples.",
    course: "RS108",
    lessons: [
      {
        _id: "L2301",
        name: "Communication Methods",
        description: "Linguistic mediation, ceremonial protocols, and non-verbal communication systems.",
        module: "M802",
      },
      {
        _id: "L2302",
        name: "Challenges in Communication",
        description: "Cultural misunderstandings, linguistic barriers, and historical prejudices affecting diplomacy.",
        module: "M802",
      },
      {
        _id: "L2303",
        name: "Case Studies",
        description: "Detailed examination of successful and failed diplomatic missions throughout history.",
        module: "M802",
      },
    ],
  },
  {
    _id: "M803",
    name: "Conflict Resolution",
    description: "Mediation strategies, peace-building processes, and post-conflict reconciliation in multi-species contexts.",
    course: "RS108",
  },
];